// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ96H1AhaqjRdaj20JnT0fMdw50V8jN-U',
    appId: '1:958033695842:web:993104796f7f6a0b1f6d3b',
    messagingSenderId: '958033695842',
    projectId: 'flutterfire-cli-sample-d5a40',
    authDomain: 'flutterfire-cli-sample-d5a40.firebaseapp.com',
    storageBucket: 'flutterfire-cli-sample-d5a40.appspot.com',
    measurementId: 'G-9D5TLFRYRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8pbN2zCEftSuJFMkUvg2-IR8ykz7qJQI',
    appId: '1:958033695842:android:b2f55f808df89bee1f6d3b',
    messagingSenderId: '958033695842',
    projectId: 'flutterfire-cli-sample-d5a40',
    storageBucket: 'flutterfire-cli-sample-d5a40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHI-nvbsB29aicQTkOHrxmD_evvekjmrA',
    appId: '1:958033695842:ios:e14a66eebc085dac1f6d3b',
    messagingSenderId: '958033695842',
    projectId: 'flutterfire-cli-sample-d5a40',
    storageBucket: 'flutterfire-cli-sample-d5a40.appspot.com',
    iosClientId: '958033695842-e4hliiqqa7q3180n35himr0vc91e8uv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireCliSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHI-nvbsB29aicQTkOHrxmD_evvekjmrA',
    appId: '1:958033695842:ios:e14a66eebc085dac1f6d3b',
    messagingSenderId: '958033695842',
    projectId: 'flutterfire-cli-sample-d5a40',
    storageBucket: 'flutterfire-cli-sample-d5a40.appspot.com',
    iosClientId: '958033695842-e4hliiqqa7q3180n35himr0vc91e8uv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireCliSample',
  );
}
